"use strict"
//password
let password= "mypassword123";
if(password.length>8){
    console.log("Your password is strong");
    
}
let color="red";
if(color=="red"|| color=="green" || color=="blue"){
    console.log("color is a primary color");
    
}
else{
    console.log(" dont found");
    
}
let y=-5;
if(y<0){
    console.log("y is negative number");
    
}
else{
    console.log("y is positive number");
    
}
let list =[1,2,3];
if(list.isArray()){
    console.log(" yes it is an array");
    
}
else{
    console.log(" not an array");
}